
### LIBRARY
library(dplyr)

LOCATION <- 0

# set working directory
if (LOCATION == 1) {
  work_dir <- 'D:\\DISSERTATION\\ANALYSIS\\STATISTICAL_MODELS\\DORRY_ONLY\\'
} else {
  work_dir <- 'F:\\DISSERTATION\\ANALYSIS\\STATISTICAL_MODELS\\DORRY_ONLY\\'
}

setwd(work_dir)


################################################################################
####################### MERGE IN SAVED LATENT FACTOR SCORES (FROM Mplus)

#AT THIS POINT, YOU SHOULD ALREADY HAVE SAVED THE LATENT FACTOR SCORES IN YOUR 
#MPLUS SCRIPT. YOU MUST HAVE ADDED A NUMERIC ID IN THE INPUT AND FACTOR ESTIMATION
#SO YOU CAN PAIR THEM BACK TO THE OVERALL DF. SAVE THE FACTOR SCORES TO A TEXT FILE. 
#NOTE THE ORDER OF VARIABLES AT THE END OF THE MPLUS OUTPUT! 

# THE FOLLOWING EXAMPLE WAS FOR ESTIMATIN P-FACTOR

################# P-FACTOR, PARENT-REPORT

## 1) LOAD IN THE MPLUS-SAVED TXT FILE AS A TABLE:

PAR_PFAC_T1_T2 <- read.table("F:\\DISSERTATION\\ANALYSIS\\STATISTICAL_MODELS\\DORRY_ONLY\\SEM\\MEASUREMENT_MODELS\\P_FACTOR_DORRY.txt", header = FALSE)

## 2) SUBSET THE DF TO JUST THE ID COLUMN AND THE DESIRED LATENT VARIABLES 
# YOU MUST KNOW THE ORDER THEY WERE SAVE (I.E., THE END OF THE OUTPUT SCRIPT!) TO
# DO THIS STEP.  

PAR_PFAC_T1_T2_RED <- PAR_PFAC_T1_T2[, c("V11", "V13", "V15")]

## 3) RENAME THE VARIABLES TO BE MORE IDENTIABLE (AT THIS POINT, MATCH THE ID NAME TO ORIGNAL FORMAT)

colnames(PAR_PFAC_T1_T2_RED) <- c("Pfac_P1", "Pfac_P2", "ID")


################################################################################
#################### MERGE DATA TOGETHER  

# LOAD IN ORIGINAL DF THAT YOU WANT TO ADD THE LATENT VARIABLE SCORE TO  

ADV_DF <- read.csv("DISSERTATION_ADVERSITY_DORRY_7.6.25.csv")

# MERGE INTO THE ORIGINAL DF (YOU MAY WANT TO left_join() if you have differences in N)

FULL_DF <- full_join(ADV_DF, PAR_PFAC_T1_T2_RED, by = "ID")

## SAVE DAT SHIT

write.csv(FULL_DF, "DISSERTATION_ALL_SURVEY_DATA_DORRY_7.6.25.csv", row.names=FALSE, na="")

